"""One-off: re-run the competitor keyword + GEO scan for a SINGLE page/date.

keyword_scan.py always loops over every page in PAGES. This reuses its logic
(scan_page, keyword sets, GEO signals) to refresh ONLY one slug for one date,
then merges the result back into reports/keyword-history.json and regenerates
reports/keyword-history.js.

Use after serp_one.py has repopulated that day's top_10_competitors.

Usage (PowerShell):
    python kwscan_one.py
    python kwscan_one.py 2026-06-23   # optional explicit date
"""
import json
import os
import sys
from datetime import datetime

import keyword_scan as ks  # imports cleanly: its main() is guarded by __main__

TARGET_URL = "https://avanaplasticsurgery.com/breast-implants-miami"


def main():
    date = sys.argv[1] if len(sys.argv) > 1 else datetime.now(ks.MIAMI).strftime("%Y-%m-%d")

    cfg = ks.PAGES.get(TARGET_URL)
    if not cfg:
        raise SystemExit(f"{TARGET_URL} is not in keyword_scan.PAGES")
    slug = cfg["slug"]

    report_path = f"reports/{date}.json"
    if not os.path.exists(report_path):
        raise SystemExit(f"no report file: {report_path}")
    with open(report_path, encoding="utf-8") as fh:
        report = json.load(fh)
    item = next((r for r in report if r.get("target_url") == TARGET_URL), None)
    if not item:
        raise SystemExit(f"no report row for {TARGET_URL} in {report_path}")

    n_comp = len(item.get("top_10_competitors", []))
    print(f"Scanning {slug} for {date} ({n_comp} competitors in report)...")

    hist_path = "reports/keyword-history.json"
    with open(hist_path, encoding="utf-8") as fh:
        history = json.load(fh)

    entry = history.get(slug, {})
    scan = ks.scan_page(TARGET_URL, cfg, item, date, entry)

    entry["keyword"] = item.get("keyword", "")
    entry["target_url"] = TARGET_URL
    entry["lang"] = cfg["lang"]
    entry["keywords"] = [label for label, _ in cfg["kw"]]
    scans = entry.get("scans", {})
    scans[date] = scan
    entry["scans"] = scans
    history[slug] = entry

    with open(hist_path, "w", encoding="utf-8") as fh:
        json.dump(history, fh, ensure_ascii=False)

    js = "// Auto-generated by keyword_scan.py — do not edit manually\n"
    js += "window.KEYWORD_HISTORY = " + json.dumps(history, ensure_ascii=False) + ";\n"
    with open("reports/keyword-history.js", "w", encoding="utf-8") as fh:
        fh.write(js)

    print(f"Done. {slug} {date}: {len(scan['sites'])} sites, "
          f"geo for {sum(1 for g in scan['geo'] if g)} column(s).")


if __name__ == "__main__":
    main()
