// Auto-generated by seo_check.py — do not edit manually
window.SEO_POSITION_DATA = {
  "https://avanaplasticsurgery.com/lipo-360-miami": {
    "series": [
      {
        "date": "2026-06-06",
        "position": null,
        "keyword": "lipo 360 miami"
      },
      {
        "date": "2026-06-07",
        "position": null,
        "keyword": "lipo 360 miami"
      },
      {
        "date": "2026-06-08",
        "position": null,
        "keyword": "lipo 360 miami"
      },
      {
        "date": "2026-06-09",
        "position": null,
        "keyword": "lipo 360 miami"
      },
      {
        "date": "2026-06-10",
        "position": null,
        "keyword": "lipo 360 miami"
      },
      {
        "date": "2026-06-11",
        "position": null,
        "keyword": "lipo 360 miami"
      },
      {
        "date": "2026-06-12",
        "position": null,
        "keyword": "lipo 360 miami"
      }
    ],
    "competitors": [
      {
        "url": "https://iconcosmeticcenter.com/360-lipo-miami",
        "title": "Lipo 360 Miami - Best Price $3000 - Icon Cosmetic Center",
        "domain": "iconcosmeticcenter.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 1
          },
          {
            "date": "2026-06-07",
            "position": 1
          },
          {
            "date": "2026-06-08",
            "position": 1
          },
          {
            "date": "2026-06-09",
            "position": 1
          },
          {
            "date": "2026-06-10",
            "position": 1
          },
          {
            "date": "2026-06-11",
            "position": 1
          },
          {
            "date": "2026-06-12",
            "position": 1
          }
        ]
      },
      {
        "url": "https://miamilifecosmetic.com/procedure/lipo-360/",
        "title": "Lipo 360 – Miami Life Cosmetic Surgery",
        "domain": "miamilifecosmetic.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 2
          },
          {
            "date": "2026-06-07",
            "position": 2
          },
          {
            "date": "2026-06-08",
            "position": 2
          },
          {
            "date": "2026-06-09",
            "position": 2
          },
          {
            "date": "2026-06-10",
            "position": 3
          },
          {
            "date": "2026-06-11",
            "position": 2
          },
          {
            "date": "2026-06-12",
            "position": 2
          }
        ]
      },
      {
        "url": "https://miaaesthetics.com/cosmetic-plastic-surgery/body/lipo-360/",
        "title": "Lipo 360 | Mia Aesthetics",
        "domain": "miaaesthetics.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 3
          },
          {
            "date": "2026-06-07",
            "position": 3
          },
          {
            "date": "2026-06-08",
            "position": 3
          },
          {
            "date": "2026-06-09",
            "position": 3
          },
          {
            "date": "2026-06-10",
            "position": 2
          },
          {
            "date": "2026-06-11",
            "position": 3
          },
          {
            "date": "2026-06-12",
            "position": 3
          }
        ]
      },
      {
        "url": "https://www.thesecretplasticsurgery.com/body-plastic-surgery-miami/lipo-360-miami/",
        "title": "Lipo 360 Miami - The Secret Plastic Surgery",
        "domain": "thesecretplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 4
          },
          {
            "date": "2026-06-07",
            "position": 5
          },
          {
            "date": "2026-06-08",
            "position": 5
          },
          {
            "date": "2026-06-09",
            "position": 7
          },
          {
            "date": "2026-06-10",
            "position": 6
          },
          {
            "date": "2026-06-11",
            "position": 5
          },
          {
            "date": "2026-06-12",
            "position": 4
          }
        ]
      },
      {
        "url": "https://prestigeplasticsurgery.com/blog/what-is-lipo-360-and-how-much/",
        "title": "Understanding Lipo 360: Costs and Results in Miami",
        "domain": "prestigeplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": null
          },
          {
            "date": "2026-06-07",
            "position": null
          },
          {
            "date": "2026-06-08",
            "position": 6
          },
          {
            "date": "2026-06-09",
            "position": 6
          },
          {
            "date": "2026-06-10",
            "position": 5
          },
          {
            "date": "2026-06-11",
            "position": 4
          },
          {
            "date": "2026-06-12",
            "position": 5
          }
        ]
      },
      {
        "url": "https://juventuscosmeticsurgery.com/lipo-360-miami-prices-recovery-results/",
        "title": "Lipo 360 in Miami: prices and recovery - Juventus Cosmetic Surgery",
        "domain": "juventuscosmeticsurgery.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 6
          },
          {
            "date": "2026-06-07",
            "position": 6
          },
          {
            "date": "2026-06-08",
            "position": 7
          },
          {
            "date": "2026-06-09",
            "position": 8
          },
          {
            "date": "2026-06-10",
            "position": 7
          },
          {
            "date": "2026-06-11",
            "position": 6
          },
          {
            "date": "2026-06-12",
            "position": 6
          }
        ]
      },
      {
        "url": "https://revivesurgery.com/body/lipo-360/",
        "title": "Lipo 360 in Miami, FL | Revive Plastic Surgery",
        "domain": "revivesurgery.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": null
          },
          {
            "date": "2026-06-07",
            "position": null
          },
          {
            "date": "2026-06-08",
            "position": null
          },
          {
            "date": "2026-06-09",
            "position": null
          },
          {
            "date": "2026-06-10",
            "position": 9
          },
          {
            "date": "2026-06-11",
            "position": 8
          },
          {
            "date": "2026-06-12",
            "position": 7
          }
        ]
      },
      {
        "url": "https://chopraplasticsurgery.com/body/liposuction-360/",
        "title": "Liposuction 360 Miami | Lipo in Miami, FL - Chopra Plastic Surgery",
        "domain": "chopraplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 5
          },
          {
            "date": "2026-06-07",
            "position": 7
          },
          {
            "date": "2026-06-08",
            "position": 9
          },
          {
            "date": "2026-06-09",
            "position": 10
          },
          {
            "date": "2026-06-10",
            "position": null
          },
          {
            "date": "2026-06-11",
            "position": 7
          },
          {
            "date": "2026-06-12",
            "position": 8
          }
        ]
      },
      {
        "url": "https://www.instagram.com/reel/DXxDqNBssfj/",
        "title": "Lipo 360 doesn't just remove fat. It sculpts your entire silhouette. By ...",
        "domain": "instagram.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": null
          },
          {
            "date": "2026-06-07",
            "position": null
          },
          {
            "date": "2026-06-08",
            "position": null
          },
          {
            "date": "2026-06-09",
            "position": null
          },
          {
            "date": "2026-06-10",
            "position": null
          },
          {
            "date": "2026-06-11",
            "position": null
          },
          {
            "date": "2026-06-12",
            "position": 9
          }
        ]
      },
      {
        "url": "https://www.realself.com/find/Florida/Miami/Lipo-360",
        "title": "Top Lipo 360 Doctors in Miami, FL - Realself",
        "domain": "realself.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": null
          },
          {
            "date": "2026-06-07",
            "position": 9
          },
          {
            "date": "2026-06-08",
            "position": 10
          },
          {
            "date": "2026-06-09",
            "position": null
          },
          {
            "date": "2026-06-10",
            "position": null
          },
          {
            "date": "2026-06-11",
            "position": 9
          },
          {
            "date": "2026-06-12",
            "position": 10
          }
        ]
      }
    ]
  },
  "https://avanaplasticsurgery.com/espanol/lipo-360-en-miami": {
    "series": [
      {
        "date": "2026-06-06",
        "position": 1,
        "keyword": "liposucción 360 en miami"
      },
      {
        "date": "2026-06-07",
        "position": 1,
        "keyword": "liposucción 360 en miami"
      },
      {
        "date": "2026-06-08",
        "position": 1,
        "keyword": "liposucción 360 en miami"
      },
      {
        "date": "2026-06-09",
        "position": 1,
        "keyword": "liposucción 360 en miami"
      },
      {
        "date": "2026-06-10",
        "position": 1,
        "keyword": "liposucción 360 en miami"
      },
      {
        "date": "2026-06-11",
        "position": 1,
        "keyword": "liposucción 360 en miami"
      },
      {
        "date": "2026-06-12",
        "position": 1,
        "keyword": "liposucción 360 en miami"
      }
    ],
    "competitors": [
      {
        "url": "https://avanaplasticsurgery.com/espanol/lipo-360-en-miami",
        "title": "Lipo 360 Miami - $3000 Mejor Precio - Avana Plastic Surgery",
        "domain": "avanaplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 1
          },
          {
            "date": "2026-06-07",
            "position": 1
          },
          {
            "date": "2026-06-08",
            "position": 1
          },
          {
            "date": "2026-06-09",
            "position": 1
          },
          {
            "date": "2026-06-10",
            "position": 1
          },
          {
            "date": "2026-06-11",
            "position": 1
          },
          {
            "date": "2026-06-12",
            "position": 1
          }
        ]
      },
      {
        "url": "https://www.thesecretplasticsurgery.com/es/cirugia-plastica-corporal-miami/lipoescultura-360-miami/",
        "title": "Lipoescultura 360 en Miami - The Secret Plastic Surgery",
        "domain": "thesecretplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 2
          },
          {
            "date": "2026-06-07",
            "position": 2
          },
          {
            "date": "2026-06-08",
            "position": 2
          },
          {
            "date": "2026-06-09",
            "position": 2
          },
          {
            "date": "2026-06-10",
            "position": 2
          },
          {
            "date": "2026-06-11",
            "position": 2
          },
          {
            "date": "2026-06-12",
            "position": 2
          }
        ]
      },
      {
        "url": "https://miamilifecosmetic.com/procedure/lipo-360/",
        "title": "Lipo 360 – Miami Life Cosmetic Surgery",
        "domain": "miamilifecosmetic.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 5
          },
          {
            "date": "2026-06-07",
            "position": 3
          },
          {
            "date": "2026-06-08",
            "position": 3
          },
          {
            "date": "2026-06-09",
            "position": 4
          },
          {
            "date": "2026-06-10",
            "position": 3
          },
          {
            "date": "2026-06-11",
            "position": 3
          },
          {
            "date": "2026-06-12",
            "position": 3
          }
        ]
      },
      {
        "url": "https://daviddelgadocirujano.com/lipo-360-miami/",
        "title": "Lipo 360 Miami : ¿Es realmente la mejor opción? - Dr David Delgado",
        "domain": "daviddelgadocirujano.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 4
          },
          {
            "date": "2026-06-07",
            "position": 4
          },
          {
            "date": "2026-06-08",
            "position": 4
          },
          {
            "date": "2026-06-09",
            "position": 3
          },
          {
            "date": "2026-06-10",
            "position": 5
          },
          {
            "date": "2026-06-11",
            "position": 8
          },
          {
            "date": "2026-06-12",
            "position": 4
          }
        ]
      },
      {
        "url": "https://iconcosmeticcenter.com/es/liposuccion-360-en-miami",
        "title": "Liposucción 360 en Miami - Icon Cosmetic Center",
        "domain": "iconcosmeticcenter.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 3
          },
          {
            "date": "2026-06-07",
            "position": 5
          },
          {
            "date": "2026-06-08",
            "position": 5
          },
          {
            "date": "2026-06-09",
            "position": 5
          },
          {
            "date": "2026-06-10",
            "position": 4
          },
          {
            "date": "2026-06-11",
            "position": 4
          },
          {
            "date": "2026-06-12",
            "position": 5
          }
        ]
      },
      {
        "url": "https://miaaesthetics.com/cosmetic-plastic-surgery/body/lipo-360/",
        "title": "Lipo 360 | Mia Aesthetics",
        "domain": "miaaesthetics.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 7
          },
          {
            "date": "2026-06-07",
            "position": 6
          },
          {
            "date": "2026-06-08",
            "position": 10
          },
          {
            "date": "2026-06-09",
            "position": 6
          },
          {
            "date": "2026-06-10",
            "position": 10
          },
          {
            "date": "2026-06-11",
            "position": 7
          },
          {
            "date": "2026-06-12",
            "position": 6
          }
        ]
      },
      {
        "url": "https://juventuscosmeticsurgery.com/es/lipo-360-miami-precios-recuperacion-resultados/",
        "title": "Lipo 360 en Miami: precios y recuperación | Juventus",
        "domain": "juventuscosmeticsurgery.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 6
          },
          {
            "date": "2026-06-07",
            "position": 8
          },
          {
            "date": "2026-06-08",
            "position": 6
          },
          {
            "date": "2026-06-09",
            "position": 8
          },
          {
            "date": "2026-06-10",
            "position": 6
          },
          {
            "date": "2026-06-11",
            "position": 6
          },
          {
            "date": "2026-06-12",
            "position": 7
          }
        ]
      },
      {
        "url": "https://www.instagram.com/p/DXxDqNBssfj/",
        "title": "Lipo 360 doesn't just remove fat. It sculpts your entire silhouette. By ...",
        "domain": "instagram.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": null
          },
          {
            "date": "2026-06-07",
            "position": null
          },
          {
            "date": "2026-06-08",
            "position": null
          },
          {
            "date": "2026-06-09",
            "position": null
          },
          {
            "date": "2026-06-10",
            "position": null
          },
          {
            "date": "2026-06-11",
            "position": null
          },
          {
            "date": "2026-06-12",
            "position": 8
          }
        ]
      },
      {
        "url": "https://revivesurgery.com/body/lipo-360/",
        "title": "Lipo 360 in Miami, FL | Revive Plastic Surgery",
        "domain": "revivesurgery.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 10
          },
          {
            "date": "2026-06-07",
            "position": 10
          },
          {
            "date": "2026-06-08",
            "position": 9
          },
          {
            "date": "2026-06-09",
            "position": 9
          },
          {
            "date": "2026-06-10",
            "position": 9
          },
          {
            "date": "2026-06-11",
            "position": 10
          },
          {
            "date": "2026-06-12",
            "position": 9
          }
        ]
      },
      {
        "url": "https://chopraplasticsurgery.com/es/body/liposuction-360/",
        "title": "Liposucción 360 Miami | Chopra Cirugía Plástica",
        "domain": "chopraplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 9
          },
          {
            "date": "2026-06-07",
            "position": 9
          },
          {
            "date": "2026-06-08",
            "position": 8
          },
          {
            "date": "2026-06-09",
            "position": 7
          },
          {
            "date": "2026-06-10",
            "position": 7
          },
          {
            "date": "2026-06-11",
            "position": null
          },
          {
            "date": "2026-06-12",
            "position": 10
          }
        ]
      }
    ]
  },
  "https://avanaplasticsurgery.com/breast-implants-miami": {
    "series": [
      {
        "date": "2026-06-06",
        "position": null,
        "keyword": "breast implants miami"
      },
      {
        "date": "2026-06-07",
        "position": null,
        "keyword": "breast implants miami"
      },
      {
        "date": "2026-06-08",
        "position": null,
        "keyword": "breast implants miami"
      },
      {
        "date": "2026-06-09",
        "position": null,
        "keyword": "breast implants miami"
      },
      {
        "date": "2026-06-10",
        "position": null,
        "keyword": "breast implants miami"
      },
      {
        "date": "2026-06-11",
        "position": null,
        "keyword": "breast implants miami"
      },
      {
        "date": "2026-06-12",
        "position": null,
        "keyword": "breast implants miami"
      }
    ],
    "competitors": [
      {
        "url": "https://www.cgcosmetic.com/",
        "title": "Miami Plastic Surgery Center, Top Plastic Surgeons",
        "domain": "cgcosmetic.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 1
          },
          {
            "date": "2026-06-07",
            "position": 1
          },
          {
            "date": "2026-06-08",
            "position": 1
          },
          {
            "date": "2026-06-09",
            "position": 1
          },
          {
            "date": "2026-06-10",
            "position": 1
          },
          {
            "date": "2026-06-11",
            "position": 1
          },
          {
            "date": "2026-06-12",
            "position": 1
          }
        ]
      },
      {
        "url": "https://miamiplasticsurgery.com/surgical-services/breast-chest/breast-augmentation/",
        "title": "Miami Breast Implants | Miami Plastic Surgery",
        "domain": "miamiplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 2
          },
          {
            "date": "2026-06-07",
            "position": 2
          },
          {
            "date": "2026-06-08",
            "position": 2
          },
          {
            "date": "2026-06-09",
            "position": 2
          },
          {
            "date": "2026-06-10",
            "position": 2
          },
          {
            "date": "2026-06-11",
            "position": 2
          },
          {
            "date": "2026-06-12",
            "position": 2
          }
        ]
      },
      {
        "url": "https://www.lhochsteinmd.com/",
        "title": "Miami Florida Plastic Surgeon | Leonard M. Hochstein M.D.",
        "domain": "lhochsteinmd.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 3
          },
          {
            "date": "2026-06-07",
            "position": 3
          },
          {
            "date": "2026-06-08",
            "position": 3
          },
          {
            "date": "2026-06-09",
            "position": 3
          },
          {
            "date": "2026-06-10",
            "position": 3
          },
          {
            "date": "2026-06-11",
            "position": 3
          },
          {
            "date": "2026-06-12",
            "position": 3
          }
        ]
      },
      {
        "url": "https://spectrum-aesthetics.com/breast-augmentation/",
        "title": "Breast Implants Miami - Breast Augmentation Cost $2300",
        "domain": "spectrum-aesthetics.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 4
          },
          {
            "date": "2026-06-07",
            "position": 4
          },
          {
            "date": "2026-06-08",
            "position": 4
          },
          {
            "date": "2026-06-09",
            "position": 4
          },
          {
            "date": "2026-06-10",
            "position": 4
          },
          {
            "date": "2026-06-11",
            "position": 4
          },
          {
            "date": "2026-06-12",
            "position": 4
          }
        ]
      },
      {
        "url": "https://drgcosmeticsurgery.com/gummy-bear-breast-implants/",
        "title": "Gummy Bear Breast Implants - Miami - DRG Cosmetic Surgery",
        "domain": "drgcosmeticsurgery.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 5
          },
          {
            "date": "2026-06-07",
            "position": 5
          },
          {
            "date": "2026-06-08",
            "position": 5
          },
          {
            "date": "2026-06-09",
            "position": 5
          },
          {
            "date": "2026-06-10",
            "position": 5
          },
          {
            "date": "2026-06-11",
            "position": 5
          },
          {
            "date": "2026-06-12",
            "position": 5
          }
        ]
      },
      {
        "url": "https://iconcosmeticcenter.com/breast-augmentation-miami",
        "title": "Breast Augmentation Miami - Icon Cosmetic Center",
        "domain": "iconcosmeticcenter.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": null
          },
          {
            "date": "2026-06-07",
            "position": null
          },
          {
            "date": "2026-06-08",
            "position": null
          },
          {
            "date": "2026-06-09",
            "position": null
          },
          {
            "date": "2026-06-10",
            "position": null
          },
          {
            "date": "2026-06-11",
            "position": 6
          },
          {
            "date": "2026-06-12",
            "position": 6
          }
        ]
      },
      {
        "url": "https://www.thesecretplasticsurgery.com/breast-plastic-surgery/breast-augmentation-miami/",
        "title": "Breast augmentation Miami - The Secret Plastic Surgery",
        "domain": "thesecretplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 6
          },
          {
            "date": "2026-06-07",
            "position": 6
          },
          {
            "date": "2026-06-08",
            "position": 6
          },
          {
            "date": "2026-06-09",
            "position": 6
          },
          {
            "date": "2026-06-10",
            "position": 6
          },
          {
            "date": "2026-06-11",
            "position": 7
          },
          {
            "date": "2026-06-12",
            "position": 7
          }
        ]
      },
      {
        "url": "https://www.realself.com/find/Florida/Miami/Breast-Augmentation",
        "title": "Top Breast Augmentation Doctors in Miami, FL - Realself",
        "domain": "realself.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 9
          },
          {
            "date": "2026-06-07",
            "position": 8
          },
          {
            "date": "2026-06-08",
            "position": 8
          },
          {
            "date": "2026-06-09",
            "position": 9
          },
          {
            "date": "2026-06-10",
            "position": 9
          },
          {
            "date": "2026-06-11",
            "position": 8
          },
          {
            "date": "2026-06-12",
            "position": 8
          }
        ]
      },
      {
        "url": "https://4beauty.net/breast-implants/",
        "title": "Breast Implants in Miami - 4Beauty Aesthetic Institute",
        "domain": "4beauty.net",
        "series": [
          {
            "date": "2026-06-06",
            "position": 8
          },
          {
            "date": "2026-06-07",
            "position": 10
          },
          {
            "date": "2026-06-08",
            "position": null
          },
          {
            "date": "2026-06-09",
            "position": 7
          },
          {
            "date": "2026-06-10",
            "position": null
          },
          {
            "date": "2026-06-11",
            "position": 9
          },
          {
            "date": "2026-06-12",
            "position": 9
          }
        ]
      },
      {
        "url": "https://www.arykraumd.com/breast-surgery/miami-breast-augmentation/",
        "title": "Breast Augmentation Miami FL - Breast Implant Surgeon Miami",
        "domain": "arykraumd.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 7
          },
          {
            "date": "2026-06-07",
            "position": 7
          },
          {
            "date": "2026-06-08",
            "position": 7
          },
          {
            "date": "2026-06-09",
            "position": 8
          },
          {
            "date": "2026-06-10",
            "position": 7
          },
          {
            "date": "2026-06-11",
            "position": 10
          },
          {
            "date": "2026-06-12",
            "position": 10
          }
        ]
      }
    ]
  },
  "https://avanaplasticsurgery.com/espanol/implantes-de-senos-en-miami": {
    "series": [
      {
        "date": "2026-06-06",
        "position": null,
        "keyword": "implantes de senos en miami"
      },
      {
        "date": "2026-06-07",
        "position": null,
        "keyword": "implantes de senos en miami"
      },
      {
        "date": "2026-06-08",
        "position": null,
        "keyword": "implantes de senos en miami"
      },
      {
        "date": "2026-06-09",
        "position": null,
        "keyword": "implantes de senos en miami"
      },
      {
        "date": "2026-06-10",
        "position": null,
        "keyword": "implantes de senos en miami"
      },
      {
        "date": "2026-06-11",
        "position": null,
        "keyword": "implantes de senos en miami"
      },
      {
        "date": "2026-06-12",
        "position": null,
        "keyword": "implantes de senos en miami"
      }
    ],
    "competitors": [
      {
        "url": "https://miamiplasticsurgery.com/es/surgical-services/breast-chest/breast-augmentation/",
        "title": "Implantes mamarios en Miami | Cirugía Plástica Miami",
        "domain": "miamiplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 1
          },
          {
            "date": "2026-06-07",
            "position": 1
          },
          {
            "date": "2026-06-08",
            "position": 1
          },
          {
            "date": "2026-06-09",
            "position": 1
          },
          {
            "date": "2026-06-10",
            "position": 1
          },
          {
            "date": "2026-06-11",
            "position": 1
          },
          {
            "date": "2026-06-12",
            "position": 1
          }
        ]
      },
      {
        "url": "https://avanaplasticsurgery.com/espanol/aumento-de-senos-miami",
        "title": "Aumento de Senos Miami $2799 - Fl | Avana Plastic Surgery",
        "domain": "avanaplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 3
          },
          {
            "date": "2026-06-07",
            "position": 3
          },
          {
            "date": "2026-06-08",
            "position": 3
          },
          {
            "date": "2026-06-09",
            "position": 3
          },
          {
            "date": "2026-06-10",
            "position": 3
          },
          {
            "date": "2026-06-11",
            "position": 3
          },
          {
            "date": "2026-06-12",
            "position": 2
          }
        ]
      },
      {
        "url": "https://www.careagaplasticsurgery.com/es/aumento-de-senos/",
        "title": "Aumento de Senos - Miami, FL - Careaga Plastic Surgery",
        "domain": "careagaplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 2
          },
          {
            "date": "2026-06-07",
            "position": 2
          },
          {
            "date": "2026-06-08",
            "position": 2
          },
          {
            "date": "2026-06-09",
            "position": 2
          },
          {
            "date": "2026-06-10",
            "position": 2
          },
          {
            "date": "2026-06-11",
            "position": 2
          },
          {
            "date": "2026-06-12",
            "position": 3
          }
        ]
      },
      {
        "url": "https://www.arykraumd.com/espanol/aumento-de-senos/",
        "title": "Cirujano plástico dedicado al aumento de senos en Miami, FL",
        "domain": "arykraumd.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 4
          },
          {
            "date": "2026-06-07",
            "position": 4
          },
          {
            "date": "2026-06-08",
            "position": 4
          },
          {
            "date": "2026-06-09",
            "position": 4
          },
          {
            "date": "2026-06-10",
            "position": 4
          },
          {
            "date": "2026-06-11",
            "position": 4
          },
          {
            "date": "2026-06-12",
            "position": 4
          }
        ]
      },
      {
        "url": "https://aeris.co/es/procedimientos/senos/aumento-de-senos/",
        "title": "Best Aumento de Senos Miami, FL | Aeris",
        "domain": "aeris.co",
        "series": [
          {
            "date": "2026-06-06",
            "position": 8
          },
          {
            "date": "2026-06-07",
            "position": 8
          },
          {
            "date": "2026-06-08",
            "position": 8
          },
          {
            "date": "2026-06-09",
            "position": 8
          },
          {
            "date": "2026-06-10",
            "position": 8
          },
          {
            "date": "2026-06-11",
            "position": 8
          },
          {
            "date": "2026-06-12",
            "position": 5
          }
        ]
      },
      {
        "url": "https://iconcosmeticcenter.com/es/aumento-de-senos-miami",
        "title": "Aumento de Senos en miami - Icon Cosmetic Center",
        "domain": "iconcosmeticcenter.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 5
          },
          {
            "date": "2026-06-07",
            "position": 5
          },
          {
            "date": "2026-06-08",
            "position": 5
          },
          {
            "date": "2026-06-09",
            "position": 5
          },
          {
            "date": "2026-06-10",
            "position": 6
          },
          {
            "date": "2026-06-11",
            "position": 6
          },
          {
            "date": "2026-06-12",
            "position": 6
          }
        ]
      },
      {
        "url": "https://www.thesecretplasticsurgery.com/es/cirugia-plastica-de-senos/levantamiento-de-senos-en-miami/",
        "title": "Levantamiento de senos Miami - The Secret Plastic Surgery",
        "domain": "thesecretplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 6
          },
          {
            "date": "2026-06-07",
            "position": 6
          },
          {
            "date": "2026-06-08",
            "position": 6
          },
          {
            "date": "2026-06-09",
            "position": 6
          },
          {
            "date": "2026-06-10",
            "position": 7
          },
          {
            "date": "2026-06-11",
            "position": 7
          },
          {
            "date": "2026-06-12",
            "position": 7
          }
        ]
      },
      {
        "url": "https://epicplasticsurgery.com/sp/senos/aumento-de-senos/",
        "title": "Aumento de Senos en Miami | Epic Cirugía Plástica",
        "domain": "epicplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 7
          },
          {
            "date": "2026-06-07",
            "position": 7
          },
          {
            "date": "2026-06-08",
            "position": 7
          },
          {
            "date": "2026-06-09",
            "position": 7
          },
          {
            "date": "2026-06-10",
            "position": 9
          },
          {
            "date": "2026-06-11",
            "position": 9
          },
          {
            "date": "2026-06-12",
            "position": 8
          }
        ]
      },
      {
        "url": "https://www.cgcosmetic.com/aumento-de-senos-miami/",
        "title": "Miami Cirugia Plastica, Aumento de Senos $2500",
        "domain": "cgcosmetic.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": 9
          },
          {
            "date": "2026-06-07",
            "position": 9
          },
          {
            "date": "2026-06-08",
            "position": 9
          },
          {
            "date": "2026-06-09",
            "position": 9
          },
          {
            "date": "2026-06-10",
            "position": 5
          },
          {
            "date": "2026-06-11",
            "position": 5
          },
          {
            "date": "2026-06-12",
            "position": 9
          }
        ]
      },
      {
        "url": "https://www.youtube.com/watch?v=eIaaIufhMAo",
        "title": "Implantes de senos en My Cosmetic Surgery Miami - YouTube",
        "domain": "youtube.com",
        "series": [
          {
            "date": "2026-06-06",
            "position": null
          },
          {
            "date": "2026-06-07",
            "position": 10
          },
          {
            "date": "2026-06-08",
            "position": 10
          },
          {
            "date": "2026-06-09",
            "position": 10
          },
          {
            "date": "2026-06-10",
            "position": 10
          },
          {
            "date": "2026-06-11",
            "position": 10
          },
          {
            "date": "2026-06-12",
            "position": 10
          }
        ]
      }
    ]
  },
  "https://avanaplasticsurgery.com/brazilian-butt-lift-miami": {
    "series": [
      {
        "date": "2026-06-07",
        "position": 1,
        "keyword": "brazilian butt lift miami"
      },
      {
        "date": "2026-06-08",
        "position": 1,
        "keyword": "brazilian butt lift miami"
      },
      {
        "date": "2026-06-09",
        "position": 1,
        "keyword": "brazilian butt lift miami"
      },
      {
        "date": "2026-06-10",
        "position": 1,
        "keyword": "brazilian butt lift miami"
      },
      {
        "date": "2026-06-11",
        "position": 1,
        "keyword": "brazilian butt lift miami"
      },
      {
        "date": "2026-06-12",
        "position": 1,
        "keyword": "brazilian butt lift miami"
      }
    ],
    "competitors": [
      {
        "url": "https://avanaplasticsurgery.com/brazilian-butt-lift-miami",
        "title": "Brazilian Butt Lift Miami - $3499 BBL Fat Transfer",
        "domain": "avanaplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-07",
            "position": 1
          },
          {
            "date": "2026-06-08",
            "position": 1
          },
          {
            "date": "2026-06-09",
            "position": 1
          },
          {
            "date": "2026-06-10",
            "position": 1
          },
          {
            "date": "2026-06-11",
            "position": 1
          },
          {
            "date": "2026-06-12",
            "position": 1
          }
        ]
      },
      {
        "url": "https://spectrum-aesthetics.com/brazilian-butt-lift/",
        "title": "Brazilian Butt Lift Miami | BBL Miami Cost $3200 - Spectrum Aesthetics",
        "domain": "spectrum-aesthetics.com",
        "series": [
          {
            "date": "2026-06-07",
            "position": 2
          },
          {
            "date": "2026-06-08",
            "position": 2
          },
          {
            "date": "2026-06-09",
            "position": 2
          },
          {
            "date": "2026-06-10",
            "position": 2
          },
          {
            "date": "2026-06-11",
            "position": 2
          },
          {
            "date": "2026-06-12",
            "position": 2
          }
        ]
      },
      {
        "url": "https://www.themaercksinstitute.com/plastic-surgery-miami-fl/men/body/brazilian-butt-lift/",
        "title": "Brazilian Butt Lift Miami, FL | The Maercks Institute",
        "domain": "themaercksinstitute.com",
        "series": [
          {
            "date": "2026-06-07",
            "position": 7
          },
          {
            "date": "2026-06-08",
            "position": 4
          },
          {
            "date": "2026-06-09",
            "position": 4
          },
          {
            "date": "2026-06-10",
            "position": 8
          },
          {
            "date": "2026-06-11",
            "position": 4
          },
          {
            "date": "2026-06-12",
            "position": 3
          }
        ]
      },
      {
        "url": "https://aeris.co/plastic-surgeons-miami-fl/body/brazilian-butt-lift/",
        "title": "Best Brazilian Butt Lift Miami, FL | Aeris",
        "domain": "aeris.co",
        "series": [
          {
            "date": "2026-06-07",
            "position": 3
          },
          {
            "date": "2026-06-08",
            "position": 3
          },
          {
            "date": "2026-06-09",
            "position": 3
          },
          {
            "date": "2026-06-10",
            "position": 3
          },
          {
            "date": "2026-06-11",
            "position": 3
          },
          {
            "date": "2026-06-12",
            "position": 4
          }
        ]
      },
      {
        "url": "https://www.cgcosmetic.com/brazilian-butt-lift-miami-fat-transfer/",
        "title": "Brazilian Butt Lift Miami, BBL From $3,500 - CG Cosmetic Surgery",
        "domain": "cgcosmetic.com",
        "series": [
          {
            "date": "2026-06-07",
            "position": 4
          },
          {
            "date": "2026-06-08",
            "position": 5
          },
          {
            "date": "2026-06-09",
            "position": 5
          },
          {
            "date": "2026-06-10",
            "position": 4
          },
          {
            "date": "2026-06-11",
            "position": 5
          },
          {
            "date": "2026-06-12",
            "position": 5
          }
        ]
      },
      {
        "url": "https://iconcosmeticcenter.com/brazilian-butt-lift-miami",
        "title": "Best Brazilian Butt Lift Miami | Icon Cosmetic Center",
        "domain": "iconcosmeticcenter.com",
        "series": [
          {
            "date": "2026-06-07",
            "position": 5
          },
          {
            "date": "2026-06-08",
            "position": 6
          },
          {
            "date": "2026-06-09",
            "position": 6
          },
          {
            "date": "2026-06-10",
            "position": 5
          },
          {
            "date": "2026-06-11",
            "position": 6
          },
          {
            "date": "2026-06-12",
            "position": 6
          }
        ]
      },
      {
        "url": "https://wtriggsmd.com/brazilian-buttlift-liposuction-with-fat-transfer-to-buttocks-hips/",
        "title": "Brazilian Buttlift (Liposuction With Fat Transfer To Buttocks & Hips)",
        "domain": "wtriggsmd.com",
        "series": [
          {
            "date": "2026-06-07",
            "position": null
          },
          {
            "date": "2026-06-08",
            "position": null
          },
          {
            "date": "2026-06-09",
            "position": null
          },
          {
            "date": "2026-06-10",
            "position": null
          },
          {
            "date": "2026-06-11",
            "position": null
          },
          {
            "date": "2026-06-12",
            "position": 7
          }
        ]
      },
      {
        "url": "https://www.thesecretplasticsurgery.com/body-plastic-surgery-miami/brazilian-butt-lift-miami/",
        "title": "Brazilian Butt Lift Miami - The Secret Plastic Surgery",
        "domain": "thesecretplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-07",
            "position": 6
          },
          {
            "date": "2026-06-08",
            "position": 7
          },
          {
            "date": "2026-06-09",
            "position": 7
          },
          {
            "date": "2026-06-10",
            "position": 6
          },
          {
            "date": "2026-06-11",
            "position": 7
          },
          {
            "date": "2026-06-12",
            "position": 8
          }
        ]
      },
      {
        "url": "https://laclinique-privee.com/brazilian-butt-lift/",
        "title": "Brazilian Butt Lift - La Clinique Privée Plastic Surgery Miami",
        "domain": "laclinique-privee.com",
        "series": [
          {
            "date": "2026-06-07",
            "position": null
          },
          {
            "date": "2026-06-08",
            "position": 8
          },
          {
            "date": "2026-06-09",
            "position": null
          },
          {
            "date": "2026-06-10",
            "position": 9
          },
          {
            "date": "2026-06-11",
            "position": null
          },
          {
            "date": "2026-06-12",
            "position": 9
          }
        ]
      },
      {
        "url": "https://miamilifecosmetic.com/procedure/brazilian-butt-lift/",
        "title": "Brazilian Butt Lift – Miami Life Cosmetic Surgery",
        "domain": "miamilifecosmetic.com",
        "series": [
          {
            "date": "2026-06-07",
            "position": 8
          },
          {
            "date": "2026-06-08",
            "position": 9
          },
          {
            "date": "2026-06-09",
            "position": 8
          },
          {
            "date": "2026-06-10",
            "position": 7
          },
          {
            "date": "2026-06-11",
            "position": 8
          },
          {
            "date": "2026-06-12",
            "position": 10
          }
        ]
      }
    ]
  },
  "https://avanaplasticsurgery.com/breast-augmentation-miami": {
    "series": [
      {
        "date": "2026-06-07",
        "position": null,
        "keyword": "breast augmentation miami"
      },
      {
        "date": "2026-06-08",
        "position": null,
        "keyword": "breast augmentation miami"
      },
      {
        "date": "2026-06-09",
        "position": null,
        "keyword": "breast augmentation miami"
      },
      {
        "date": "2026-06-10",
        "position": null,
        "keyword": "breast augmentation miami"
      },
      {
        "date": "2026-06-11",
        "position": null,
        "keyword": "breast augmentation miami"
      },
      {
        "date": "2026-06-12",
        "position": null,
        "keyword": "breast augmentation miami"
      }
    ],
    "competitors": [
      {
        "url": "https://www.cgcosmetic.com/",
        "title": "Miami Plastic Surgery Center, Top Plastic Surgeons",
        "domain": "cgcosmetic.com",
        "series": [
          {
            "date": "2026-06-07",
            "position": 1
          },
          {
            "date": "2026-06-08",
            "position": 1
          },
          {
            "date": "2026-06-09",
            "position": 1
          },
          {
            "date": "2026-06-10",
            "position": 1
          },
          {
            "date": "2026-06-11",
            "position": 1
          },
          {
            "date": "2026-06-12",
            "position": 1
          }
        ]
      },
      {
        "url": "https://www.lhochsteinmd.com/",
        "title": "Miami Florida Plastic Surgeon | Leonard M. Hochstein M.D.",
        "domain": "lhochsteinmd.com",
        "series": [
          {
            "date": "2026-06-07",
            "position": 2
          },
          {
            "date": "2026-06-08",
            "position": 2
          },
          {
            "date": "2026-06-09",
            "position": 2
          },
          {
            "date": "2026-06-10",
            "position": 2
          },
          {
            "date": "2026-06-11",
            "position": 2
          },
          {
            "date": "2026-06-12",
            "position": 2
          }
        ]
      },
      {
        "url": "https://www.arykraumd.com/breast-surgery/miami-breast-augmentation/",
        "title": "Breast Augmentation Miami FL - Breast Implant Surgeon Miami",
        "domain": "arykraumd.com",
        "series": [
          {
            "date": "2026-06-07",
            "position": 3
          },
          {
            "date": "2026-06-08",
            "position": 3
          },
          {
            "date": "2026-06-09",
            "position": 3
          },
          {
            "date": "2026-06-10",
            "position": 3
          },
          {
            "date": "2026-06-11",
            "position": 3
          },
          {
            "date": "2026-06-12",
            "position": 3
          }
        ]
      },
      {
        "url": "https://miamiplasticsurgery.com/",
        "title": "Miami Plastic Surgery: Expert Plastic Surgery in Miami, FL",
        "domain": "miamiplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-07",
            "position": 10
          },
          {
            "date": "2026-06-08",
            "position": 10
          },
          {
            "date": "2026-06-09",
            "position": 10
          },
          {
            "date": "2026-06-10",
            "position": 10
          },
          {
            "date": "2026-06-11",
            "position": 4
          },
          {
            "date": "2026-06-12",
            "position": 4
          }
        ]
      },
      {
        "url": "https://www.thesecretplasticsurgery.com/breast-plastic-surgery/breast-augmentation-miami/",
        "title": "Breast augmentation Miami - The Secret Plastic Surgery",
        "domain": "thesecretplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-07",
            "position": 5
          },
          {
            "date": "2026-06-08",
            "position": 5
          },
          {
            "date": "2026-06-09",
            "position": 5
          },
          {
            "date": "2026-06-10",
            "position": 5
          },
          {
            "date": "2026-06-11",
            "position": 5
          },
          {
            "date": "2026-06-12",
            "position": 5
          }
        ]
      },
      {
        "url": "https://drgcosmeticsurgery.com/gummy-bear-breast-implants/",
        "title": "Gummy Bear Breast Implants - Miami - DRG Cosmetic Surgery",
        "domain": "drgcosmeticsurgery.com",
        "series": [
          {
            "date": "2026-06-07",
            "position": null
          },
          {
            "date": "2026-06-08",
            "position": null
          },
          {
            "date": "2026-06-09",
            "position": null
          },
          {
            "date": "2026-06-10",
            "position": null
          },
          {
            "date": "2026-06-11",
            "position": null
          },
          {
            "date": "2026-06-12",
            "position": 6
          }
        ]
      },
      {
        "url": "https://iconcosmeticcenter.com/breast-augmentation-miami",
        "title": "Breast Augmentation Miami - Icon Cosmetic Center",
        "domain": "iconcosmeticcenter.com",
        "series": [
          {
            "date": "2026-06-07",
            "position": null
          },
          {
            "date": "2026-06-08",
            "position": null
          },
          {
            "date": "2026-06-09",
            "position": null
          },
          {
            "date": "2026-06-10",
            "position": null
          },
          {
            "date": "2026-06-11",
            "position": 6
          },
          {
            "date": "2026-06-12",
            "position": 7
          }
        ]
      },
      {
        "url": "https://www.gablesplasticsurgery.com/breast/breast-augmentation/",
        "title": "Best Breast Augmentation in Miami, FL | Gables Plastic Surgery",
        "domain": "gablesplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-07",
            "position": 7
          },
          {
            "date": "2026-06-08",
            "position": 7
          },
          {
            "date": "2026-06-09",
            "position": 6
          },
          {
            "date": "2026-06-10",
            "position": 7
          },
          {
            "date": "2026-06-11",
            "position": 8
          },
          {
            "date": "2026-06-12",
            "position": 8
          }
        ]
      },
      {
        "url": "https://www.realself.com/find/Florida/Miami/Breast-Augmentation",
        "title": "Top Breast Augmentation Doctors in Miami, FL - Realself",
        "domain": "realself.com",
        "series": [
          {
            "date": "2026-06-07",
            "position": 9
          },
          {
            "date": "2026-06-08",
            "position": 8
          },
          {
            "date": "2026-06-09",
            "position": 9
          },
          {
            "date": "2026-06-10",
            "position": 8
          },
          {
            "date": "2026-06-11",
            "position": 9
          },
          {
            "date": "2026-06-12",
            "position": 9
          }
        ]
      },
      {
        "url": "https://therealdrmiami.com/",
        "title": "Dr. Miami | Plastic Surgery Miami | Dr. Michael Salzhauer | Plastic ...",
        "domain": "therealdrmiami.com",
        "series": [
          {
            "date": "2026-06-07",
            "position": 4
          },
          {
            "date": "2026-06-08",
            "position": 4
          },
          {
            "date": "2026-06-09",
            "position": 4
          },
          {
            "date": "2026-06-10",
            "position": 4
          },
          {
            "date": "2026-06-11",
            "position": 10
          },
          {
            "date": "2026-06-12",
            "position": 10
          }
        ]
      }
    ]
  },
  "https://avanaplasticsurgery.com/espanol/aumento-de-senos-miami": {
    "series": [
      {
        "date": "2026-06-09",
        "position": 4,
        "keyword": "aumento de senos en miami"
      },
      {
        "date": "2026-06-10",
        "position": 4,
        "keyword": "aumento de senos en miami"
      },
      {
        "date": "2026-06-11",
        "position": 4,
        "keyword": "aumento de senos en miami"
      },
      {
        "date": "2026-06-12",
        "position": 4,
        "keyword": "aumento de senos en miami"
      }
    ],
    "competitors": [
      {
        "url": "https://miamiplasticsurgery.com/es/surgical-services/breast-chest/breast-augmentation/",
        "title": "Implantes mamarios en Miami | Cirugía Plástica Miami",
        "domain": "miamiplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-09",
            "position": 1
          },
          {
            "date": "2026-06-10",
            "position": 1
          },
          {
            "date": "2026-06-11",
            "position": 1
          },
          {
            "date": "2026-06-12",
            "position": 1
          }
        ]
      },
      {
        "url": "https://www.careagaplasticsurgery.com/es/aumento-de-senos/",
        "title": "Aumento de Senos - Miami, FL - Careaga Plastic Surgery",
        "domain": "careagaplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-09",
            "position": 2
          },
          {
            "date": "2026-06-10",
            "position": 2
          },
          {
            "date": "2026-06-11",
            "position": 2
          },
          {
            "date": "2026-06-12",
            "position": 2
          }
        ]
      },
      {
        "url": "https://www.arykraumd.com/espanol/aumento-de-senos/",
        "title": "Cirujano plástico dedicado al aumento de senos en Miami, FL",
        "domain": "arykraumd.com",
        "series": [
          {
            "date": "2026-06-09",
            "position": 3
          },
          {
            "date": "2026-06-10",
            "position": 3
          },
          {
            "date": "2026-06-11",
            "position": 3
          },
          {
            "date": "2026-06-12",
            "position": 3
          }
        ]
      },
      {
        "url": "https://avanaplasticsurgery.com/espanol/aumento-de-senos-miami",
        "title": "Aumento de Senos Miami $2799 - Fl | Avana Plastic Surgery",
        "domain": "avanaplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-09",
            "position": 4
          },
          {
            "date": "2026-06-10",
            "position": 4
          },
          {
            "date": "2026-06-11",
            "position": 4
          },
          {
            "date": "2026-06-12",
            "position": 4
          }
        ]
      },
      {
        "url": "https://www.thesecretplasticsurgery.com/es/cirugia-plastica-de-senos/levantamiento-de-senos-en-miami/",
        "title": "Levantamiento de senos Miami - The Secret Plastic Surgery",
        "domain": "thesecretplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-09",
            "position": 5
          },
          {
            "date": "2026-06-10",
            "position": 5
          },
          {
            "date": "2026-06-11",
            "position": 5
          },
          {
            "date": "2026-06-12",
            "position": 5
          }
        ]
      },
      {
        "url": "https://iconcosmeticcenter.com/es/aumento-de-senos-miami",
        "title": "Aumento de Senos en miami - Icon Cosmetic Center",
        "domain": "iconcosmeticcenter.com",
        "series": [
          {
            "date": "2026-06-09",
            "position": 6
          },
          {
            "date": "2026-06-10",
            "position": 6
          },
          {
            "date": "2026-06-11",
            "position": 6
          },
          {
            "date": "2026-06-12",
            "position": 6
          }
        ]
      },
      {
        "url": "https://aeris.co/es/procedimientos/senos/aumento-de-senos/",
        "title": "Best Aumento de Senos Miami, FL | Aeris",
        "domain": "aeris.co",
        "series": [
          {
            "date": "2026-06-09",
            "position": 8
          },
          {
            "date": "2026-06-10",
            "position": 7
          },
          {
            "date": "2026-06-11",
            "position": 7
          },
          {
            "date": "2026-06-12",
            "position": 7
          }
        ]
      },
      {
        "url": "https://miamiplasticsurgery.com/es/fat-transfer-miami-breast-enhancement/",
        "title": "Procedimiento de transferencia de grasa natural para el aumento de ...",
        "domain": "miamiplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-09",
            "position": null
          },
          {
            "date": "2026-06-10",
            "position": null
          },
          {
            "date": "2026-06-11",
            "position": null
          },
          {
            "date": "2026-06-12",
            "position": 8
          }
        ]
      },
      {
        "url": "https://epicplasticsurgery.com/sp/senos/aumento-de-senos/",
        "title": "Aumento de Senos en Miami | Epic Cirugía Plástica",
        "domain": "epicplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-09",
            "position": 7
          },
          {
            "date": "2026-06-10",
            "position": 8
          },
          {
            "date": "2026-06-11",
            "position": 8
          },
          {
            "date": "2026-06-12",
            "position": 9
          }
        ]
      },
      {
        "url": "https://www.cgcosmetic.com/aumento-de-senos-miami/",
        "title": "Miami Cirugia Plastica, Aumento de Senos $2500",
        "domain": "cgcosmetic.com",
        "series": [
          {
            "date": "2026-06-09",
            "position": 9
          },
          {
            "date": "2026-06-10",
            "position": 9
          },
          {
            "date": "2026-06-11",
            "position": 9
          },
          {
            "date": "2026-06-12",
            "position": 10
          }
        ]
      }
    ]
  },
  "https://avanaplasticsurgery.com/espanol/levantamiento-de-gluteos-en-miami": {
    "series": [
      {
        "date": "2026-06-09",
        "position": null,
        "keyword": "levantamiento de gluteos brasileño en miami"
      },
      {
        "date": "2026-06-10",
        "position": 9,
        "keyword": "levantamiento de gluteos brasileño en miami"
      },
      {
        "date": "2026-06-11",
        "position": null,
        "keyword": "levantamiento de gluteos brasileño en miami"
      },
      {
        "date": "2026-06-12",
        "position": 1,
        "keyword": "levantamiento de gluteos brasileño en miami"
      }
    ],
    "competitors": [
      {
        "url": "https://avanaplasticsurgery.com/espanol/levantamiento-de-gluteos-en-miami",
        "title": "Levantamiento de Glúteos Brasileño en Miami - Avana Plastic Surgery",
        "domain": "avanaplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-09",
            "position": null
          },
          {
            "date": "2026-06-10",
            "position": 9
          },
          {
            "date": "2026-06-11",
            "position": null
          },
          {
            "date": "2026-06-12",
            "position": 1
          }
        ]
      },
      {
        "url": "https://aeris.co/es/procedimientos/cuerpo/levantamiento-de-gluteos-brasileno/",
        "title": "Best Levantamiento de Glúteos Brasileño Miami, FL | Aeris",
        "domain": "aeris.co",
        "series": [
          {
            "date": "2026-06-09",
            "position": 2
          },
          {
            "date": "2026-06-10",
            "position": 2
          },
          {
            "date": "2026-06-11",
            "position": 2
          },
          {
            "date": "2026-06-12",
            "position": 2
          }
        ]
      },
      {
        "url": "https://miamiplasticsurgery.com/es/surgical-services/body/buttock-augmentation/",
        "title": "Levantamiento de glúteos brasileño en Miami, FL",
        "domain": "miamiplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-09",
            "position": 1
          },
          {
            "date": "2026-06-10",
            "position": 1
          },
          {
            "date": "2026-06-11",
            "position": 1
          },
          {
            "date": "2026-06-12",
            "position": 3
          }
        ]
      },
      {
        "url": "https://www.thesecretplasticsurgery.com/es/cirugia-plastica-corporal-miami/aumento-de-gluteos-en-miami/",
        "title": "Aumento de glúteos en Miami - The Secret Plastic Surgery",
        "domain": "thesecretplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-09",
            "position": 3
          },
          {
            "date": "2026-06-10",
            "position": 3
          },
          {
            "date": "2026-06-11",
            "position": 3
          },
          {
            "date": "2026-06-12",
            "position": 4
          }
        ]
      },
      {
        "url": "https://epicplasticsurgery.com/sp/cuerpo/levantamiento-de-gl%C3%BAteos-brasile%C3%B1o/",
        "title": "Levantamiento de Glúteos Brasileño en Miami | Epic Cirugía Plástica",
        "domain": "epicplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-09",
            "position": 7
          },
          {
            "date": "2026-06-10",
            "position": 6
          },
          {
            "date": "2026-06-11",
            "position": 5
          },
          {
            "date": "2026-06-12",
            "position": 5
          }
        ]
      },
      {
        "url": "https://es.brandonplasticsurgery.com/brazilian-butt-lift/",
        "title": "Levantamiento de glúteos brasileño en Tampa, Florida",
        "domain": "es.brandonplasticsurgery.com",
        "series": [
          {
            "date": "2026-06-09",
            "position": 5
          },
          {
            "date": "2026-06-10",
            "position": 5
          },
          {
            "date": "2026-06-11",
            "position": 7
          },
          {
            "date": "2026-06-12",
            "position": 6
          }
        ]
      },
      {
        "url": "https://www.youtube.com/watch?v=SCqS5OHCIfY",
        "title": "Testimonio de BBL: Levantamiento de Glúteos Brasileño - YouTube",
        "domain": "youtube.com",
        "series": [
          {
            "date": "2026-06-09",
            "position": 6
          },
          {
            "date": "2026-06-10",
            "position": 7
          },
          {
            "date": "2026-06-11",
            "position": 6
          },
          {
            "date": "2026-06-12",
            "position": 7
          }
        ]
      },
      {
        "url": "https://iconcosmeticcenter.com/es/revision-de-levantamiento-de-gluteos-en-miami",
        "title": "Revisión de Aumento de Glúteos en Miami | Icon Cosmetic Center",
        "domain": "iconcosmeticcenter.com",
        "series": [
          {
            "date": "2026-06-09",
            "position": 4
          },
          {
            "date": "2026-06-10",
            "position": 4
          },
          {
            "date": "2026-06-11",
            "position": 4
          },
          {
            "date": "2026-06-12",
            "position": 8
          }
        ]
      },
      {
        "url": "https://elpais.com/us/2025-10-27/miami-se-afianza-como-capital-del-lifting-brasileno-de-gluteos.html",
        "title": "BBL: Miami se afianza como capital del 'lifting' brasileño de glúteos",
        "domain": "elpais.com",
        "series": [
          {
            "date": "2026-06-09",
            "position": 8
          },
          {
            "date": "2026-06-10",
            "position": 10
          },
          {
            "date": "2026-06-11",
            "position": 8
          },
          {
            "date": "2026-06-12",
            "position": 9
          }
        ]
      },
      {
        "url": "https://www.arcplasticsurgeons.com/es/blog/levantamiento-de-gluteos-brasileno-aumento-de-gluteos-miami/",
        "title": "Levantamiento de glúteos brasileño - ARC Plastic Surgery",
        "domain": "arcplasticsurgeons.com",
        "series": [
          {
            "date": "2026-06-09",
            "position": 10
          },
          {
            "date": "2026-06-10",
            "position": 8
          },
          {
            "date": "2026-06-11",
            "position": null
          },
          {
            "date": "2026-06-12",
            "position": 10
          }
        ]
      }
    ]
  }
};
