// Auto-generated by seo_check.py — do not edit manually
window.SEO_POSITION_DATA = {
  "https://avanaplasticsurgery.com/lipo-360-miami": [
    {
      "date": "2026-06-06",
      "position": null,
      "keyword": "lipo 360 miami"
    },
    {
      "date": "2026-06-07",
      "position": null,
      "keyword": "lipo 360 miami"
    }
  ],
  "https://avanaplasticsurgery.com/espanol/lipo-360-en-miami": [
    {
      "date": "2026-06-06",
      "position": 1,
      "keyword": "liposucción 360 en miami"
    },
    {
      "date": "2026-06-07",
      "position": 1,
      "keyword": "liposucción 360 en miami"
    }
  ],
  "https://avanaplasticsurgery.com/breast-implants-miami": [
    {
      "date": "2026-06-06",
      "position": null,
      "keyword": "breast implants miami"
    },
    {
      "date": "2026-06-07",
      "position": null,
      "keyword": "breast implants miami"
    }
  ],
  "https://avanaplasticsurgery.com/espanol/implantes-de-senos-en-miami": [
    {
      "date": "2026-06-06",
      "position": null,
      "keyword": "implantes de senos en miami"
    },
    {
      "date": "2026-06-07",
      "position": null,
      "keyword": "implantes de senos en miami"
    }
  ]
};
